### ISSUE TITLE
Resource/ResourceGroup name should be unique

### ISSUE THREAD

**Issue by joesteeve** [froyg/thittam#47]
Currently there is no check on the 'name' provided by the user. It should be unique.

**Comment by EvenCode** [comment]
resource-group.cxx and resource-manager.cxx takes care of "resource name" to be unique.

bool
ResourceManager::is_unique_group_name (const std::string & group_name)

bool
ResourceGroup::is_unique_resource_name (const std::string & resource_name)

**Comment by joesteeve** [comment]
These should be used by the controller to check before adding. If the name is not unique, a message should be shown and the 'add-form' should be shown again.

**Comment by EvenCode** [comment]
@Compro-Prasad

**Comment by Compro-Prasad** [comment]
I think, "text changed" signal in the dialog box can be regularly passed to the model for checking if the name is unique. Will look through the code to get back with a proper solution.
