### ISSUE TITLE
Trim spaces in resource and resource group names

### ISSUE THREAD

**Issue by Compro-Prasad** [froyg/thittam#53]

**Comment by EvenCode** [comment]
just trim space from beginning and end or should we restrict use of spaces entirely ? cause currently six spaces is a valid name :D

**Comment by Compro-Prasad** [comment]
Okay, we can remove all punctuations.

**Comment by EvenCode** [comment]
ok doing it.

**Comment by EvenCode** [comment]
> Okay, we can remove all punctuations.

@Compro-Prasad what if some person's name is D'Arcy ? let's allow all other special char.

**Comment by Compro-Prasad** [comment]
As you wish. Characters are limited though.
