### ISSUE TITLE
astyle config - parentheses padding

### ISSUE THREAD

**Issue by EvenCode** [froyg/thittam#55]
In current .astylrc

line : 14 -> --pad-paren (http://astyle.sourceforge.net/astyle.html#_pad-paren)

and

line 18 -> --pad-first-paren-out (http://astyle.sourceforge.net/astyle.html#_pad-first-paren-out)

these are not required as discussed, so will be removed.

Agree ?

**Comment by Compro-Prasad** [comment]
Doesn't work for me

**Comment by EvenCode** [comment]
checking again ...

**Comment by Compro-Prasad** [comment]
It worked the previous day but not today. Don't know why.
